---
# APP CONFIGURATION: ##################
# CODIUM: #############################
- name: Add Codium to Bash  
  tags: [customisation, terminal, codium]
  become_user: '{{ username }}'
  ansible.builtin.lineinfile:
    path: ~/.bashrc
    line: alias codium="flatpak run com.vscodium.codium "

- name: Codium Extensions
  tags: [codium]
  become_user: wolf
  ansible.builtin.shell: codium --install-extension '{{ item }}'
  with_items: '{{ codium_extensions }}'
  
# STARSHIP: ###########################
# ADD COPR: 
- name: Add Starship COPR
  tags: [customisation, terminal]
  community.general.copr:
    name: atim/starship
    state: enabled

# INSTALL: 
- name: Install Starship Shell Prompt
  tags: [customisation, terminal]
  ansible.builtin.dnf:
    name: starship 
    state: present

# ADD PROFILES: 
- name: Add Starship to Profiles 
  tags: [customisation, terminal]
  become_user: '{{ username }}'
  ansible.builtin.lineinfile:
    path: ~/.bashrc
    line: eval "$(starship init bash)"

