---
# APP-CONFIG VARIABLES: ###############
# VS Codium Extensions: ###############
codium_extensions: 
  - eamodio.gitlens
  - hashicorp.terraform
  - ms-python.python
  - ms-vscode.azure-account
  - ms-vscode.powershell-preview
  - PKief.material-icon-theme
  - redhat.ansible
  - redhat.vscode-yaml
  - yzhang.markdown-all-in-one