---
# FLATPAKS: ###########################
# ENABLE FLAKPAK REPO: ################
- name: Enable FlatPak Repo
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    method: system
    enabled: true

# INSTALL FLATPAKS: ###################
- name: Install Flatpak Packages
  community.general.flatpak:
    name: '{{ item }}'
    state: present
    method: system
  loop: '{{ flatpaks }}'
