---
# DESKTOP CUSTOMISATIONS VARS: ########
#
# https://github.com/vinceliuice/Graphite-gtk-theme:
# 
# Requires:
#
#    GTK >=3.20
#    gnome-themes-extra (or gnome-themes-standard)
#    Murrine engine — The package name depends on the distro.
#        gtk-engine-murrine on Arch Linux
#        gtk-murrine-engine on Fedora
#        gtk2-engine-murrine on openSUSE
#        gtk2-engines-murrine on Debian, Ubuntu, etc.
#    sassc — build dependency
#    Icon theme Tela-circle-icon-theme

# Theme dependencies.
dependencies: 
  - gnome-themes-extra
  - gtk-murrine-engine
  - python3-psutil
  - sassc

# Theme repos and where to store.
theme: 
  repo: git@github.com:vinceliuice/Graphite-gtk-theme.git
  destination: Graphite 

cursors: 
  repo: git@github.com:vinceliuice/Graphite-cursors.git
  destination: Cursors 

icons: 
  repo: git@github.com:vinceliuice/Tela-circle-icon-theme.git
  destination: Icons 

# Wallpaper:
# Expected location under user.local/share/backgrounds.
wallpaper: 
  picture-uri: 'file:~/.local/share/backgrounds/wave-Dark-fedora.png'
  picture-uri-dark: 'file:~/.local/share/backgrounds/wave-Dark-fedora.png'


# Used to set the theme with dconf.
interface:
  color-scheme: 'prefer-dark'
  cursor-theme: 'Graphite-dark-cursors'
  gtk-theme: 'Graphite-Dark'
  icon-theme: 'Tela-circle-dark'

# FileChooser:
fileChooser:
  show-hidden: true
  sort-directories-first: true

numlock: true