---
# DESKTOP CUSTOMISATIONS TASK: ########
# THEME: ##############################
- name: Install Theme Dependencies
  tags: [theme]
  ansible.builtin.dnf:
    name: '{{ item }}'
    state: present
  loop: '{{ dependencies }}'

- name: Clone Theme 
  tags: [theme, testing]
  become_user: '{{ username }}'
  ansible.builtin.git:
    repo: '{{ theme.repo }}'
    dest: ~/DevOps/Theme/{{ theme.destination }}

- name: Install Theme 
  tags: [theme]
  become_user: '{{ username }}'
  command: ~/DevOps/Theme/{{ theme.destination }}/install.sh


# ICONS: ##############################
- name: Clone Icons  
  tags: [theme, icons, testing]
  become_user: '{{ username }}'
  ansible.builtin.git:
    repo: '{{ icons.repo }}'
    dest: ~/DevOps/Theme/{{ icons.destination }} 
    
- name: Install Icons 
  tags: [theme, icons]
  become_user: '{{ username }}'
  command: ~/DevOps/Theme/{{ icons.destination }}/install.sh -c

# CURSORS: ############################
- name: Clone Cursors 
  tags: [theme, cursors, testing]
  become_user: '{{ username }}'
  ansible.builtin.git:
    repo: '{{ cursors.repo }}'
    dest: ~/DevOps/Theme/{{ cursors.destination }} 

# The cursor install script prompts the user.
- name: Install Cursors 
  tags: [theme, cursors]
  become_user: '{{ username }}'
  expect: 
    command: ~/DevOps/Theme/{{ cursors.destination }}/install.sh
    responses:
      Question:
        - 1

# WALLPAPER: ##########################
- name: Install Wallpaper 
  tags: [theme, wallpaper]
  become_user: '{{ username }}'
  command: ~/DevOps/Theme/{{ theme.destination }}/wallpaper/install-wallpapers.sh

# SET THEME: ##########################
- name: Set DConf Interface 
  tags: [theme, dconf]
  community.general.dconf:
    key: "/org/gnome/desktop/interface"
    value: "[('{{ item.key }}'), ('{{ item.value }}')]"
    state: present
  loop: "{{ lookup('dict', interface) }}"

