---
# DNF VARIABLES: ######################
# REPOS: ##############################
rpm:
 - "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
 - "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"

librewolf: "https://rpm.librewolf.net/librewolf-repo.repo"

# PACKAGES: ###########################
#  - broadcom-wl removed from drivers.

drivers:
  - logiops

apps: 
  - codium 
  - discord
  - evolution
  - hugo
  - hwinfo
  - librewolf
  - lutris
  - python3-psutil
  - steam
  - timeshift

gnome: 
  - gnome-shell-extension-dash-to-dock
  - gnome-shell-extension-dash-to-panel
  - gnome-shell-extension-gsconnect
  - gnome-shell-extension-openweather
  - gnome-shell-extension-user-theme
  - gnome-tweaks
  - libgtop2-devel 
  - lm_sensors

codecs:
  - gstreamer1-libav
  - gstreamer1-plugin-openh264
  - gstreamer1-plugins-good
  - gstreamer1-plugins-good-extras
  - gstreamer1-plugins-ugly
  - gstreamer1-vaapi

# FLATPAK VARIABLES: ##################
flatpaks:
  - com.bitwarden.desktop
  - com.mattjakeman.ExtensionManager
  - io.freetubeapp.FreeTube
  - org.gimp.GIMP
  - org.signal.Signal
  - tv.plex.PlexDesktop

# UNWANTED PACKAGES: ##################
remove: 
  - cheese
  - gnome-calendar
  - gnome-contacts
  - gnome-maps
  - gnome-tour
  - rhythmbox
  - simple-scan
  