---
# DNF TASKS: ##########################
# OPTIMISE DNF: #######################
- name: Optimise DNF
  tags: [ dnf ]
  ansible.builtin.lineinfile:
    path: /etc/dnf/dnf.conf
    line: max_parallel_downloads=10

# UPDATE PACKAGES: ####################
- name: Update Installed Packages
  tags: [ dnf ]
  ansible.builtin.dnf:
    name: "*"
    state: latest

# INSTALL RPM REPOS: ##################
- name: Install RPM Repos
  tags: [apps, dnf, rpm]
  ansible.builtin.dnf:
    name: '{{ item }}'
    state: present
    disable_gpg_check: true
  loop: '{{ rpm }}'

# INSTALL LIBREWOLF FROM FILE: ########
- name: Install LibreWolf Repo
  tags: [apps, repo]
  command: dnf config-manager --add-repo '{{ librewolf }}'

# INSTALL VSCODIUM REPO: ##############
- name: Add VSCodium Repo Key
  tags: [codium, apps]
  ansible.builtin.rpm_key:
    state: present
    key: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/-/raw/master/pub.gpg
  
- name: Add VSCodium Repo
  tags: [codium, apps]
  command: printf "[gitlab.com_paulcarroty_vscodium_repo]\nname=download.vscodium.com\nbaseurl=https://download.vscodium.com/rpms/\nenabled=1\ngpgcheck=1\nrepo_gpgcheck=1\ngpgkey=https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/-/raw/master/pub.gpg\nmetadata_expire=1h" | sudo tee -a /etc/yum.repos.d/vscodium.repo

# INSTALL DRIVERS: ####################
- name: Install Required Drivers
  tags: [drivers]
  ansible.builtin.dnf:
    name: '{{ item }}'
    state: present
  loop: '{{ drivers }}'

# INSTALL APPS: #######################
- name: Install Required Applications
  tags: [apps]
  ansible.builtin.dnf:
    name: '{{ item }}'
    state: present
  loop: '{{ apps }}'

# INSTALL GNOME PACKAGES: #############
- name: Install Required Gnome Packages
  tags: [gnome, customisation]
  ansible.builtin.dnf:
    name: '{{ item }}'
    state: present
  loop: '{{ gnome }}'

# INSTALL CODECS: #####################
- name: Install CODEC Packages
  tags: [codecs]
  ansible.builtin.dnf:
    name: '{{ item }}'
    state: present
    exclude: gstreamer1-plugins-bad-free-devel
  loop: '{{ codecs }}'

# FLATPAKS: ###########################
# ENABLE FLAKPAK REPO: ################
- name: Enable FlatPak Repo
  tags: [apps, flatpaks]
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    method: system
    enabled: true

# INSTALL FLATPAKS: ###################
- name: Install Flatpak Packages
  tags: [apps, flatpaks]
  community.general.flatpak:
    name: '{{ item }}'
    state: present
    method: system
  loop: '{{ flatpaks }}'

# REMOVE PACKAGESS: ###################
- name: Remove Unwanted Packages
  tags: [cleanup, remove]
  ansible.builtin.dnf:
    name: '{{ item }}'
    state: absent
  loop: '{{ remove }}'
